/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import data.Database;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import oracle.jrockit.jfr.JFR;

/**
 *
 * @author kworkstat2
 */
public class ExamPage extends javax.swing.JFrame {
    protected static int count=1;
    protected static int total;
    protected static String exam_code;
    protected static String test_name="";
    protected static String company_name="";
    protected static int exam_time;
    protected static int test_no;
    protected static String[] questions;
    protected static String[] choice;

    
    /**
     * Creates new form ExamPage
     * @param exam_code
     * @param questions
     */
    public ExamPage(String exam_code, String[] questions) {
        initComponents();
        ExamPage.exam_code = exam_code;
        ExamPage.questions = questions;
        try {
            testInfo(exam_code);
        } catch (SQLException ex) {
            Logger.getLogger(ExamPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        finish.setVisible(false);
        qnumber.setText(count+" / "+total);
          if(count==1){
            next.setVisible(true);
            back.setVisible(false);
            finish.setVisible(false);
      
        }
       parseQuestion(count);

       execute();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        time = new java.awt.Label();
        qnumber = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        finish.setText("Testi Bitir");

        back.setText("Geri");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setText("Ýleri");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        time.setText("label1");

        qnumber.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(qnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(503, Short.MAX_VALUE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finish)
                    .addComponent(back))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(443, Short.MAX_VALUE)
                    .addComponent(next)
                    .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         
        this.count++;
        qnumber.setText(count+" / "+total);
        if(count==total){
            next.setVisible(false);
            finish.setVisible(true);
      
        }
        if(count!=1){
            back.setVisible(true);
        }
        parseQuestion(count);
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if(count==1){
            next.setVisible(true);
            back.setVisible(false);
            finish.setVisible(false);
      
        }
        else{
          this.count--;
          back.setVisible(true);
        }
        qnumber.setText(count+" / "+total);
         if(count!=total){
            next.setVisible(true);
            finish.setVisible(false);
      
        }
        parseQuestion(count);
    }//GEN-LAST:event_backActionPerformed
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPage(exam_code,questions).setVisible(true);
            }
       
        });
    }
    public void parseQuestion(int no){
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        System.out.println("*********"+questions[no-1]);
        String[] question_elements = new String[6];
                question_elements = questions[no-1].split(Pattern.quote(" $ "));
        System.out.println("****"+question_elements[1]+"****");
        if(question_elements[0].equals("Çoktan Seçmeli")){
            String[] nwchoice = new String[4];
            nwchoice[0]=question_elements[2];
            nwchoice[1]=question_elements[3];
            nwchoice[2]=question_elements[4];
            nwchoice[3]=question_elements[5];
            choice = nwchoice;
           postQuestion(no, question_elements[1], "multiple");
        }
        else if(question_elements[1].equals("Kod"))
            postQuestion(no, question_elements[1], "code");
        else if(question_elements[1].equals("Ses Kaydý"))
            postQuestion(no, question_elements[1], "voice");
        else if(question_elements[1].equals("Açýk Uçlu"))
            postQuestion(no, question_elements[1], "open");
    }
    public void createFiles(){
         String dirname="C:/InternshipER";
		File dir = new File(dirname);
		dir.mkdir();
                
                dirname="C://InternshipER//screenshots";
		File dir2 = new File(dirname);
		dir2.mkdir();
                
                dirname="C://InternshipER//network";
		File dir3 = new File(dirname);
		dir3.mkdir();
                
                dirname="C://InternshipER//exam";
		File dir4 = new File(dirname);
		dir4.mkdir();
                
                dirname="C://InternshipER//camera";
		File dir5 = new File(dirname);
		dir5.mkdir();
                
                dirname="C://InternshipER//camera//flagged";
		File dir6 = new File(dirname);
		dir6.mkdir();
                
                dirname="C://InternshipER//camera//temp";
		File dir7 = new File(dirname);
		dir7.mkdir();
                
                
    }
    public void postQuestion(int no, String question, String type){
        System.out.println("post girdi....");
        switch (type) {
            case "multiple":
                {
                    System.out.println("multi girdi...");
                    MultipleQuestion yeni = new MultipleQuestion("bla bla bla bla?",choice);
                    jPanel1.add(yeni.getContentPane());
                    break;
                }
            case "code":
                {
                    CodeQuestion yeni = new CodeQuestion(question);
                    jPanel1.add(yeni.getContentPane());
                    break;
                }
            case "voice":
                {
                    VoiceQuestion yeni = new VoiceQuestion(question);
                    jPanel1.add(yeni.getContentPane());
                    break;
                }
            case "open":
                {
                    OpenQuestion yeni = new OpenQuestion(question);
                    jPanel1.add(yeni.getContentPane());
                    break;
                }
            default:
                break;
        }
    }
    public void testInfo(String exam_code) throws SQLException{
        Database obj = new Database();
        ResultSet rs = obj.examInfos(exam_code);
        while(rs.next()){
          test_no = rs.getInt(1);
          test_name = rs.getString(3);
          total = rs.getInt(4);
          exam_time = rs.getInt(5);
          
          String company_id = rs.getString(2);
          company_name = obj.companyName(company_id);
          
        }
    }
     public static void execute() {
	ExecutorService executorService = Executors.newFixedThreadPool(3);
	//executorService.submit(FaceDetection::detectFaces);
	executorService.submit(ScreenShot::screenShotStart);
	executorService.submit(CameraSnapshot::takePicture);
	executorService.submit(NetworkSniffer::listenNetwork);
		
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton finish;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private java.awt.Label qnumber;
    private java.awt.Label time;
    // End of variables declaration//GEN-END:variables
}
