/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import java.io.File;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JTextField;

/**
 *
 * @author kworkstat2
 */
public class ExamPage extends javax.swing.JFrame {
    public static int count=1;
    public static int total=15;
    /**
     * Creates new form ExamPage
     */
    public ExamPage() {
        initComponents();
        
        finish.setVisible(false);
        qnumber.setText(count+" / "+total);
          if(count==1){
            next.setVisible(true);
            back.setVisible(false);
            finish.setVisible(false);
      
        }  
       createFiles();
       /* VoiceQuestion yeni = new VoiceQuestion("bla bla bla blblblblblblblblblbllbbllblblbl?");
        yeni.setVisible(true);
        yeni.setSize(300,300);
        this.add(yeni);*/
        execute();
    }
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        finish = new javax.swing.JButton();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();
        time = new java.awt.Label();
        qnumber = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        finish.setText("Testi Bitir");

        back.setText("Geri");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        next.setText("Ýleri");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        time.setText("label1");

        qnumber.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(qnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(8, 8, 8)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finish)
                    .addComponent(back))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(441, Short.MAX_VALUE)
                    .addComponent(next)
                    .addGap(21, 21, 21)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         
        this.count++;
        qnumber.setText(count+" / "+total);
        if(count==total){
            next.setVisible(false);
            finish.setVisible(true);
      
        }
        if(count!=1){
            back.setVisible(true);
        }
        
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if(count==1){
            next.setVisible(true);
            back.setVisible(false);
            finish.setVisible(false);
      
        }
        else{
          this.count--;
          back.setVisible(true);
        }
        qnumber.setText(count+" / "+total);
         if(count!=total){
            next.setVisible(true);
            finish.setVisible(false);
      
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
           
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPage().setVisible(true);
            }
       
        });
    }
    public void createFiles(){
         String dirname="C:/InternshipER";
		File dir = new File(dirname);
		dir.mkdir();
                
                dirname="C://InternshipER//screenshots";
		File dir2 = new File(dirname);
		dir2.mkdir();
                
                dirname="C://InternshipER//network";
		File dir3 = new File(dirname);
		dir3.mkdir();
                
                dirname="C://InternshipER//exam";
		File dir4 = new File(dirname);
		dir4.mkdir();
                
                dirname="C://InternshipER//camera";
		File dir5 = new File(dirname);
		dir5.mkdir();
                
                dirname="C://InternshipER//camera//flagged";
		File dir6 = new File(dirname);
		dir6.mkdir();
                
                dirname="C://InternshipER//camera//temp";
		File dir7 = new File(dirname);
		dir7.mkdir();
                
                
    }
    public void postQuestion(int no, String question, String type){
       
       if(type.equals("multiple")){
        String[] choice={"A","B","C","D"};
        MultipleQuestion yeni = new MultipleQuestion("bla bla bla bla?",choice);
        yeni.setVisible(true);
        yeni.setSize(300,300);
        this.add(yeni);
       }
       else  if(type.equals("code")){
        CodeQuestion yeni = new CodeQuestion("bla bla bla blblblblblblblblblbllbbllblblbl?");
        yeni.setVisible(true);
        yeni.setSize(300,300);
        this.add(yeni);
    }
       else  if(type.equals("voice")){
        VoiceQuestion yeni = new VoiceQuestion("n");
        yeni.setVisible(true);
        yeni.setSize(300,300);
        this.add(yeni);
           
       }
       else  if(type.equals("open")){
        OpenQuestion yeni = new OpenQuestion();
        yeni.setVisible(true);
        yeni.setSize(300,300);
        this.add(yeni);
       }
    }
    
     public static void execute() {
	ExecutorService executorService = Executors.newFixedThreadPool(3);
	//executorService.submit(FaceDetection::detectFaces);
	executorService.submit(ScreenShot::screenShotStart);
	executorService.submit(CameraSnapshot::takePicture);
	executorService.submit(NetworkSniffer::listenNetwork);
		
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton finish;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private java.awt.Label qnumber;
    private java.awt.Label time;
    // End of variables declaration//GEN-END:variables
}
