/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import static application.ExamPage.test_no;
import data.Database;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MesutKutlu
 */
public class ExamDetailsStart extends javax.swing.JFrame {
    protected static int total;
    protected static String exam_code;
    protected static String test_name="";
    protected static String company_name="";
    protected static int exam_time;
    protected static int test_no;

    /**
     * Creates new form ExamDetailsStart
     */
    public ExamDetailsStart(String exam_code) {
        initComponents();
        ExamDetailsStart.exam_code = exam_code;
        try {
            testInfo(exam_code);
        } catch (SQLException ex) {
            Logger.getLogger(ExamDetailsStart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        firma = new javax.swing.JLabel();
        testname = new javax.swing.JLabel();
        sure = new javax.swing.JLabel();
        soru = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user.setText("kullanýcý Hoþgeldin!");

        firma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firma.setText("firma");
        firma.setToolTipText("");

        testname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        testname.setText("test");

        sure.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sure.setText("süre");

        soru.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soru.setText("soru");

        jButton1.setText("Baþla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(237, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(testname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(firma, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(sure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(146, 146, 146))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(firma)
                .addGap(18, 18, 18)
                .addComponent(testname)
                .addGap(18, 18, 18)
                .addComponent(sure)
                .addGap(18, 18, 18)
                .addComponent(soru)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                
            ExamPage exm = new ExamPage(exam_code,getQuestions());
            exm.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamDetailsStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamDetailsStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamDetailsStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamDetailsStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamDetailsStart(exam_code).setVisible(true);
            }
        });
    }
    public String[] getQuestions(){
        Database obj = new Database();
        ResultSet rs = obj.allQuestions(Integer.toString(test_no));
        int count=1;
        String[] questions = new String[total];
        try {
            while(rs.next()){
                // question,type,choices,no
                String question ="";
                String question_text = rs.getString(1);
                String type = rs.getString(2);
                Array choicesarr = rs.getArray(3);
                String[] choices = (String[])choicesarr.getArray();
                int no = rs.getInt(4);
                
                question = type+" $ "+question_text+" $ ";                
                if(type.equals("Çoktan Seçmeli")){
                    for(int i=0;i<choices.length;i++){
                        question+=choices[i]+" $ ";
                    }
                }
                questions[no-1] = question;
            }
            return questions;
        } catch (SQLException ex) {
            Logger.getLogger(ExamDetailsStart.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }
    public void testInfo(String exam_code) throws SQLException{
        Database obj = new Database();
        ResultSet rs = obj.examInfos(exam_code);
        while(rs.next()){
          test_no = rs.getInt(1);
          test_name = rs.getString(3);
          total = rs.getInt(4);
          exam_time = rs.getInt(5);
          
          String company_id = rs.getString(2);
          company_name = obj.companyName(company_id);
        }
        soru.setText("Soru sayýsý: "+total);
        firma.setText("Firma: "+company_name);
        sure.setText("Sýnav süresi: "+total+" dakika");
        testname.setText(test_name);
        user.setText("xxxxxx  Hoþgeldin!");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel soru;
    private javax.swing.JLabel sure;
    private javax.swing.JLabel testname;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
